version: "3.7"
services:
  asp:
    image: ksi123456ab/alphabet-update-server
    tty: true
    stdin_open: true
    volumes:
      - ./volume:/volume

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "${NGINX_PORT-80}:80"
    volumes:
      - ./volume/nginx.conf:/etc/nginx/nginx.conf
      - ./volume/out:/volume/out

  vsftpd:
    image: bogem/ftp
    environment:
      FTP_USER: ${FTP_USER-admin}
      FTP_PASS: ${FTP_PASS:?ftp_pass}
      PASV_ADDRESS: ${SERVER_HOST:?host}
      LOG_STDOUT: "true"
    ports:
      - "20:20"
      - "21:21"
      - "${FTP_PASVPORT-47470}-${FTP_PASVPORT-47470}:47470-47470"
    volumes:
      - ./volume/in:/home/vsftpd