version: "3.7"
services:

  asp-install:
    image: ksi123456ab/alphabet-update-server
    tty: true
    stdin_open: true
    volumes:
      - ./volume:/volume
      - ./volume/appsettings.json:/app/appsettings.json
    profiles:
      - install
    environment:
      - "START_OPTION=INSTALL"
      - "PathBase=${ASP_PATHBASE:-/updateserver}"

  asp:
    image: ksi123456ab/alphabet-update-server
    volumes:
      - ./volume:/volume
      - ./volume/appsettings.json:/app/appsettings.json
    environment:
      - "START_OPTION=SERVER"
      - "PathBase=${ASP_PATHBASE:-/updateserver}"
      - "Logging__Console__FormatterName=Simple"
    restart: always

  # nginx:1.12-alpine
  nginx:
    image: nginx:1.12-alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./volume/nginx:/volume/nginx
      - ./volume/nginx.conf:/etc/nginx/nginx.conf
      - ./volume/out:/volume/out
    restart: always

  ftp:
    image: delfer/alpine-ftp-server
    environment:
      USERS: "${FTP_USER:-admin}|${FTP_PASS:?pass}|/home/ftp"
      ADDRESS: "${FTP_ADDR}"
      MIN_PORT: "${FTP_PASVPORT_MIN:-30000}"
      MAX_PORT: "${FTP_PASVPORT_MAX:-30010}"
    ports:
      - "${FTP_PORT_20:-20}:${FTP_PORT_20:-20}"
      - "${FTP_PORT_21:-21}:${FTP_PORT_21:-21}"
      - "${FTP_PASVPORT_MIN:-30000}-${FTP_PASVPORT_MAX:-30010}:${FTP_PASVPORT_MIN:-30000}-${FTP_PASVPORT_MAX:-30010}"
    volumes:
      - ./volume/in:/home/ftp
    restart: always

  vnstat:
    image: vergoh/vnstat:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volume/vnstat:/var/lib/vnstat
    environment:
      - HTTP_PORT=0

  vnstati:
    image: vergoh/vnstat:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volume/vnstat:/var/lib/vnstat:ro
    environment:
      - HTTP_PORT=38685
      - HTTP_LOG=/dev/stdout
      - LARGE_FONTS=0
      - CACHE_TIME=1
      - RATE_UNIT=1
      - PAGE_REFRESH=0
      - RUN_VNSTATD=0